apiVersion: v1
appVersion: "latest"
description: A Helm chart for Kubernetes gorush
name: gorush
version: 1.0.0
sources:
  - https://github.com/EENCloud/gorush
maintainers:
  - name: Brandon Reynolds
    email: breynolds@eagleeyenetworks.com
  - name: Peter Whiteside
    email: pwhiteside@eagleeyenetworks.com
